# Generated by Django 2.1 on 2018-11-16 16:25

import data_access.paysheets.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_auto_20181116_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paysheet',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveSmallIntegerField()),
                ('month', data_access.paysheets.models.IntegerRangeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaysheetDetail',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('worked_days', models.PositiveSmallIntegerField()),
                ('basic', models.FloatField()),
                ('transport_assistance', models.FloatField()),
                ('total_accrued', models.FloatField()),
                ('health_percentage', models.FloatField()),
                ('pension_percentage', models.FloatField()),
                ('healt', models.FloatField()),
                ('pension', models.FloatField()),
                ('total_deducted', models.FloatField()),
                ('paid', models.FloatField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='employees.Employee')),
                ('paysheet', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='paysheets.Paysheet')),
                ('salary', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='employees.Salary')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('basic_salary', models.FloatField()),
                ('transport_assistance', models.FloatField()),
                ('health_percentage', models.FloatField()),
                ('pension_percentage', models.FloatField()),
                ('year', models.PositiveSmallIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
