# Generated by Django 2.1 on 2018-11-16 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paysheets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paysheetdetail',
            name='cash_contributions',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paysheetdetail',
            name='health',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paysheetdetail',
            name='holidays',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paysheetdetail',
            name='occupational_hazards',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paysheetdetail',
            name='premium_services',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paysheetdetail',
            name='unemployment',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paysheetdetail',
            name='unemployment_interest',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setting',
            name='cash_contributions',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setting',
            name='holiday_percentage',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setting',
            name='occupational_hazards',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setting',
            name='premium_services',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setting',
            name='unemployment_interest',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setting',
            name='unemployment_percentage',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
