# Generated by Django 2.1 on 2018-11-17 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paysheets', '0002_auto_20181116_2256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paysheetdetail',
            name='healt',
        ),
    ]
